name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'vinicius0809'
          reponame: 'blaze-patterns'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged     